mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
      name: Jwt-SpringSecurity
      url: jdbc:mysql://localhost:3306/Jwt-SpringSecurity?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver

jwt:
  header: Authorization
  secret: JwtSecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh